### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by spock64** [mflorence99/el-3270#8]
I'm having route getting this to build. If I try a development run, in the "npm run serve" I get an error:

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

I'm not an Angular programmer, so am lost as to how this needs to be fixed - any ideas?

**Comment by mflorence99** [comment]
I apologize for that trouble. I had absolutely planned on fixing that today, by pure chance! I had updated a dependency but neglected to make the necessary changes to this project -- and a couple of others. I will make the change shortly and report back here. Many thanks for your interest in EL-3270.

**Comment by mflorence99** [comment]
@spock64 this should be fixed now. Many thanks!

**Comment by spock64** [comment]
Perfect - thanks for this. I plan to implement an ICL terminal emulator and will use this as inspiration!

**Comment by mflorence99** [comment]
Good luck @spock64 - I have followed you and will be very interested in your interpretation of the problem. I will say that if I had to do my 3270 emulator again I’d look harder at rendering in a canvas rather than using pure HTML for each character cell. I believe performance would be much more stable in production code. This was just a fun exercise though so I won’t be rushing in to that!
